CREATE UNIQUE INDEX VEICULOS_PLACA ON VEICULOS (PLACA);

CREATE INDEX MOVIMENTACOES_PLACA ON MOVIMENTACOES (PLACA);

CREATE UNIQUE INDEX MOVIMENTACOES_T ON MOVIMENTACOES (T);

CREATE UNIQUE INDEX MOVIMENTACOES_ID ON MOVIMENTACOES (ID);

CREATE UNIQUE INDEX MODELOS_ID ON MODELOS (ID);

CREATE UNIQUE INDEX CORES_ID ON CORES (ID);

CREATE VIEW DETALHES_VEICULOS AS
    SELECT VEICULOS.PLACA AS PLACA,
           MARCAS.NOME AS MARCA,
           MODELOS.NOME AS MODELO,
           CORES.NOME AS COR,
           MOVIMENTACOES.CODIGO AS CODMOV,
           MOVIMENTACOES.ID AS IDMOV,
           MOVIMENTACOES.T AS TMOV,
           VEICULOS.CREDITO AS CREDITO,
           VEICULOS.ISENTO AS ISENTO
      FROM VEICULOS
           INNER JOIN
           MOVIMENTACOES ON MOVIMENTACOES.PLACA = VEICULOS.PLACA
           INNER JOIN
           MODELOS ON MODELOS.ID = VEICULOS.ID_MODELO
           INNER JOIN
           MARCAS ON MARCAS.ID = MODELOS.ID_MARCA
           INNER JOIN
           CORES ON CORES.ID = VEICULOS.ID_COR
     WHERE MOVIMENTACOES.T = (
                                 SELECT max(T) 
                                   FROM MOVIMENTACOES
                                  WHERE MOVIMENTACOES.PLACA = VEICULOS.PLACA
                             );
