public var relatorio:String = "{\\rtf1\\ansi\\ansicpg1252\\deff0\\deflang1046\\deflangfe1046\\deftab708{\\fonttbl{\\f0\\fswiss\\fprq2\\fcharset0 Calibri;}{\\f1\\froman\\fprq2\\fcharset0 Times New Roman;}}"
+ "{\\*\\generator Msftedit 5.41.15.1515;}\\viewkind4\\uc1\\pard\\nowidctlpar\\sa200\\sl276\\slmult1\\qc\\f0\\fs44 Complexo Assistencial Dr. Hansen\\par" 
+ " Estacionamento\\par" 
+ "\\b\\par" 
+ "\\par" 
+ "\\par" 
+ "\\par" 
+ "\\fs56 Movimenta\\'e7\\'f5es de Ve\\'edculos\\par" 
+ " %abrangencia%\\par" 
+ "\\par" 
+ "\\par" 
+ "\\par" 
+ "\\par" 
+ "\\par" 
+ "\\b0\\fs24\\par" 
+ " Relat\\'f3rio gerado em %timestamp%\\par\\par" 
+ "\\pard\\nowidctlpar\\fi-360\\li218\\sa200\\sl276\\slmult1\\tx284\\b\\fs44 1.\\tab   Resumo\\par"

+ "\\pard\\nowidctlpar\\li-142\\sa200\\sl276\\slmult1\\tx567\\fs36 1.1  Informa\\'e7\\'f5es gerais\\par" 
+ "\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4381\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8931\\pard\\intbl\\nowidctlpar\\qc\\fs28 Abrang\\'eancia deste Relat\\'f3rio\\cell\\b0 %abrangencia%\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4381\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8931\\pard\\intbl\\nowidctlpar\\qc\\b Tarifa média praticada\\cell\\b0 %tarifa%\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4381\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8931\\pard\\intbl\\nowidctlpar\\qc\\b Ve\\'edculos movimentados\\cell\\b0 %nroMovimentados%\\cell\\row\\pard\\nowidctlpar\\sa200\\sl276\\slmult1\\tx284\\b\\fs20\\par" 

+ "\\pard\\nowidctlpar\\li-142\\sa200\\sl276\\slmult1\\tx567\\fs36 1.2  Despesas fixas\\par" 
+ "\\trowd\\trgaph70\\trleft-70\\trqc\\trrh223\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "%linhasDespesas%"

+ "\\par"
+ "\\pard\\nowidctlpar\\li-142\\sa200\\sl276\\slmult1\\tx567\\fs36\\b 1.3  Ve\\'edculos: isentos ou pagantes\\b0\\par" 
 
+ "\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clvertalc\\clbrdrb\\brdrw10\\brdrs \\cellx3261\\clvertalc\\clbrdrb\\brdrw10\\brdrs \\cellx6237\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8931\\pard\\intbl\\nowidctlpar\\qc\\fs28\\cell\\b0\\cell\\pard\\intbl\\nowidctlpar\\ri72\\qc\\b Arrecada\\'e7\\'e3o\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx3261\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6237\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8931\\pard\\intbl\\nowidctlpar\\qc Isentos\\cell\\b0 %nroIsentos%\\cell N/A\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx3261\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6237\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8931\\pard\\intbl\\nowidctlpar\\qc\\b Pagantes\\cell\\b0 %nroPagantes%\\cell %arrPagantes%\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx3261\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6237\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8931\\pard\\intbl\\nowidctlpar\\qc\\b Total\\cell\\fs44 %nroMovimentados%\\cell %arrPagantes%\\cell\\row\\pard\\nowidctlpar\\sa200\\sl276\\slmult1\\tx284\\fs20\\par" 
+ "\\par" 

+ "\\pard\\nowidctlpar\\li-142\\sa200\\sl276\\slmult1\\tx567\\fs36 1.4  Ve\\'edculos pagantes: com cr\\'e9dito ou sem cr\\'e9dito\\par" 
+ "\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clbrdrb\\brdrw10\\brdrs \\cellx3261\\clbrdrb\\brdrw10\\brdrs \\cellx6237\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8931\\pard\\intbl\\nowidctlpar\\qc\\fs28\\cell\\b0\\cell\\pard\\intbl\\nowidctlpar\\ri72\\qc\\b Arrecada\\'e7\\'e3o\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx3261\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6237\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8931\\pard\\intbl\\nowidctlpar\\qc Com cr\\'e9dito\\cell\\b0 %nroComCredito%\\cell N/A\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx3261\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6237\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8931\\pard\\intbl\\nowidctlpar\\qc\\b Sem cr\\'e9dito\\cell\\b0 %nroSemCredito%\\cell %arrPagantes%\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx3261\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6237\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8931\\pard\\intbl\\nowidctlpar\\qc\\b Total\\cell\\fs44 %nroPagantes%\\cell %arrPagantes%\\cell\\row\\pard\\nowidctlpar\\sa200\\sl276\\slmult1\\tx284\\fs20\\par" 
+ "\\par" 

+ "\\pard\\nowidctlpar\\li-142\\sa200\\sl276\\slmult1\\tx567\\fs36 1.5  Ve\\'edculos pagantes sem cr\\'e9dito: cobran\\'e7a na entrada ou na sa\\'edda\\par" 
+ "\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clvertalc\\clbrdrb\\brdrw10\\brdrs \\cellx3261\\clvertalc\\clbrdrb\\brdrw10\\brdrs \\cellx6237\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8931\\pard\\intbl\\nowidctlpar\\qc\\fs28\\cell\\b0\\cell\\pard\\intbl\\nowidctlpar\\ri72\\qc\\b Arrecada\\'e7\\'e3o\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx3261\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6237\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8931\\pard\\intbl\\nowidctlpar\\qc Entrada\\cell\\b0 %nroCobrEntrada%\\cell %arrCobrEntrada%\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx3261\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6237\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8931\\pard\\intbl\\nowidctlpar\\qc\\b Sa\\'edda\\cell\\b0 %nroCobrSaida%\\cell %arrCobrSaida%\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx3261\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6237\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8931\\pard\\intbl\\nowidctlpar\\qc\\b Total\\cell\\fs44 %nroSemCredito%\\cell %arrPagantes%\\cell\\row\\pard\\nowidctlpar\\li-142\\sa200\\sl276\\slmult1\\tx567\\fs36\\par" 


+ " 1.6  Ve\\'edculos: primeiro registro no banco de dados\\par" 
+ "\\trowd\\trgaph70\\trleft-70\\trqc\\trrh223\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4687\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8309\\pard\\intbl\\nowidctlpar\\qc\\fs28 Ve\\'edculos registrados pela primeira vez\\cell\\b0 %nroNovos%\\cell\\row\\pard\\nowidctlpar\\sa200\\sl276\\slmult1\\tx567\\b\\fs36\\par" 


+ "\\pard\\nowidctlpar\\li-142\\sa200\\sl276\\slmult1\\tx567 1.5  Cr\\'e9dito: concess\\'e3o e dedu\\'e7\\'e3o\\par" 
+ "\\trowd\\trgaph70\\trleft-70\\trqc\\trrh223\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx3299\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6275\\pard\\intbl\\nowidctlpar\\qc\\fs28 Concedidos\\cell\\b0 %creditoConcedido%\\cell\\row\\trowd\\trgaph70\\trleft-70\\trqc\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx3299\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6275\\pard\\intbl\\nowidctlpar\\qc\\b Deduzidos\\cell\\b0 %creditoDeduzido%\\cell\\row\\pard\\nowidctlpar\\sa200\\sl276\\slmult1\\qc\\fs24\\par" 

+ "\\pard\\nowidctlpar\\li-142\\sa200\\sl276\\slmult1\\tx567\\b\\fs36 1.7  P\\'e1tio: primeira entrada e \\'faltima sa\\'edda\\par" 
+ "\\trowd\\trgaph70\\trleft-70\\trqc\\trrh223\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clvertalc\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2106\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4799\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8866\\pard\\intbl\\nowidctlpar\\qc\\fs28\\cell Instante\\cell Ve\\'edculo\\cell\\row\\trowd\\trgaph70\\trleft-70\\trqc\\trrh223\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2106\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4799\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8866\\pard\\intbl\\nowidctlpar\\qc Primeira entrada\\cell\\b0 %tPrimeiraEntrada%\\cell %vPrimeiraEntrada%\\cell\\row\\trowd\\trgaph70\\trleft-70\\trqc\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2106\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4799\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8866\\pard\\intbl\\nowidctlpar\\qc\\b\\'daltima sa\\'edda\\cell\\b0 %tUltimaSaida%\\cell %vUltimaSaida%\\cell\\row\\pard\\nowidctlpar\\sa200\\sl276\\slmult1\\qc\\fs24\\par" 

+ "\\pard\\nowidctlpar\\fi-360\\li218\\sa200\\sl276\\slmult1\\tx284\\b\\fs44 2.\\tab   Movimenta\\'e7\\'f5es\\par" 
+ "\\pard\\nowidctlpar\\sa200\\sl276\\slmult1\\qj\\tx284\\fs20 Legenda para a coluna Cobran\\'e7a\\b0 : \\b E/SC\\b0  = na entrada, sem dedu\\'e7\\'e3o de cr\\'e9dito; \\b E/CC\\b0  = na entrada, com dedu\\'e7\\'e3o de cr\\'e9dito; \\b S/SC\\b0  = na sa\\'edda, sem dedu\\'e7\\'e3o de cr\\'e9dito; \\b S/CC \\b0 = na sa\\'edda, com dedu\\'e7\\'e3o de cr\\'e9dito; \\b I\\b0  = ve\\'edculo isento." 
+ "\\par" 
+ "\\trowd\\trgaph70\\trleft-567\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3" 
+ "\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx283\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx1133\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2409\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx3543\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4677\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6520\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8504\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9355\\pard\\intbl\\nowidctlpar\\qc\\b\\fs24 Placa\\cell C\\'f3d.\\cell Marca\\cell Modelo\\cell Cor\\cell Entrada\\cell Sa\\'edda\\cell Cobr.\\cell\\row\\trowd\\trgaph70\\trleft-567\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3"; 

public var linhaTabelaMovimentacoes:String = "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx283\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx1133\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2409\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx3543\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4677\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6520\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx8504\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9355\\pard\\intbl\\nowidctlpar\\qc\\b0\\fs16 %mPlaca%\\cell %mCod%\\cell %mMarca%\\cell %mModelo%\\cell %mCor%\\cell %mEntrada%\\cell %mSaida%\\cell %mTipoCobranca%\\cell\\row\\trowd\\trgaph70\\trleft-567\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3";

public var linhaDespesaFixa:String = "\\clvertalc\\clshdng2500\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx3299\\clvertalc\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6275\\pard\\intbl\\nowidctlpar\\qc\\b %nomeDespesa%\\cell\\b0 R$ %valorDespesa%\\cell\\row\\trowd\\trgaph70\\trleft-70\\trqc\\trrh223\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3";