public var modeloResumoDeRelatorio:String = "{\\rtf1\\ansi\\ansicpg1252\\deff0\\deflang1046{\\fonttbl{\\f0\\fswiss\\fcharset0 Arial;}}"
+ "{\\*\\generator Msftedit 5.41.15.1515;}\\viewkind4\\uc1\\pard\\f0\\fs24   ------------------------------------------------------\\par"
+ " |  \\b Complexo Assistencial Dr. Hansen\\b0\\par"
+ " |                 \\b Estacionamento\\par"
+ "\\b0 |\\par"
+ " |       \\b Resumo de Movimenta\\'e7\\'f5es\\b0\\par"
+ "\\fs20 |\\par"
+ " |     \\b Abrang\\'eancia\\b0 : %abrangencia%\\par"
+ " |     \\b Tarifa m\\'e9dia\\b0 : %tarifa%\\par"
+ " |     \\b Ve\\'edculos movimentados\\b0 : %nroMovimentados%\\par"
+ " |\\par"
+ " |     \\b Pagantes:\\b0 \\par"
+ " |      %nroPagantes% (%arrPagantes% arrecadados)\\par"
+ " | \\par"
+ " |     \\b Isentos:\\b0 \\par"
+ " |      %nroIsentos% (sem arrecadação)\\par"
+ " | \\par"
+ " |\\tab\\tab\\par"
+ " |     \\b Pagantes c/ cr\\'e9dito:\\b0 \\par"
+ " |      %nroComCredito%  (sem arrecadação)\\par"
+ " | \\par"
+ " |     \\b Pagantes s/ cr\\'e9dito:\\b0 \\par"
+ " |      %nroSemCredito% (%arrPagantes% arrecadados)\\par"
+ " | \\par"
+ " | \\par"
+ " |     \\b Pagantes s/ cr\\'e9dito c/ cobr. na entrada:\\b0  \\par"
+ " |      %nroCobrEntrada% (%arrCobrEntrada% arrecadados)\\par"
+ " | \\par"
+ " |     \\b Pagantes s/ cr\\'e9dito c/ cobr. na sa\\'edda:\\b0  \\par"
+ " |      %nroCobrSaida% (%arrCobrSaida% arrecadados)\\par"
+ " | \\par"
+ " ---------------------------------------------------------------------\\par"
+ "\\par"
+ "}";