public var modeloResumoDeRelatorio:String = "{\\rtf1\\ansi\\ansicpg1252\\deff0\\deflang1046{\\fonttbl{\\f0\\fswiss\\fcharset0 Arial;}}"
+ "{\\*\\generator Msftedit 5.41.15.1515;}\\viewkind4\\uc1\\pard\\f0\\fs24  \\tab\\tab ------------------------------------------------------\\par"
+ "\\tab\\tab |  \\b Complexo Assistencial Dr. Hansen\\b0\\par"
+ "\\tab\\tab |                 \\b Estacionamento\\par"
+ "\\b0\\tab\\tab |\\par"
+ "\\tab\\tab |       \\b Resumo de Movimenta\\'e7\\'f5es\\b0\\par"
+ "\\tab\\tab\\fs20 |\\par"
+ "\\tab\\tab |     \\b Abrang\\'eancia\\b0 : %abrangencia%\\par"
+ "\\tab\\tab |     \\b Tarifa m\\'e9dia\\b0 : %tarifa%\\par"
+ "\\tab\\tab |     \\b Ve\\'edculos movimentados\\b0 : %nroMovimentados%\\par"
+ "\\tab\\tab |\\par"
+ "\\tab\\tab |     \\b Pagantes:\\b0 \\par"
+ "\\tab\\tab |      %nroPagantes% (%arrPagantes% arrecadados)\\par"
+ "\\tab\\tab | \\par"
+ "\\tab\\tab |     \\b Isentos:\\b0 \\par"
+ "\\tab\\tab |      %nroIsentos% (sem arrecadação)\\par"
+ "\\tab\\tab | \\par"
+ "\\tab\\tab |\\tab\\tab\\par"
+ "\\tab\\tab |     \\b Pagantes c/ cr\\'e9dito:\\b0 \\par"
+ "\\tab\\tab |      %nroComCredito%  (sem arrecadação)\\par"
+ "\\tab\\tab | \\par"
+ "\\tab\\tab |     \\b Pagantes s/ cr\\'e9dito:\\b0 \\par"
+ "\\tab\\tab |      %nroSemCredito% (%arrPagantes% arrecadados)\\par"
+ "\\tab\\tab | \\par"
+ "\\tab\\tab | \\par"
+ "\\tab\\tab |     \\b Pagantes s/ cr\\'e9dito c/ cobr. na entrada:\\b0  \\par"
+ "\\tab\\tab |      %nroCobrEntrada% (%arrCobrEntrada% arrecadados)\\par"
+ "\\tab\\tab | \\par"
+ "\\tab\\tab |     \\b Pagantes s/ cr\\'e9dito c/ cobr. na sa\\'edda:\\b0  \\par"
+ "\\tab\\tab |      %nroCobrSaida% (%arrCobrSaida% arrecadados)\\par"
+ "\\tab\\tab | \\par"
+ "\\tab\\tab ---------------------------------------------------------------------\\par"
+ "\\tab\\tab\\par"
+ "}";